### ISSUE TITLE
Qitmeer crashes on launching while receiving miner connection

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#190]
1. Running a miner with the config pointing to node
2. clear node data using ./qitmeer -L
3. Launching node.

Qitmeer@Miner ~/github.com/Qitmeer/qitmeer (dev) $ ./qitmeer --connect=10.147.18.79:28130
2019-11-27|17:26:19.269 [INFO ] System info                         Qitmeer Version=0.8.2+dev Go version=go1.13.1
2019-11-27|17:26:19.270 [INFO ] System info                         UUID=9245a726-3635-4080-ba8d-632dec212616
2019-11-27|17:26:19.270 [INFO ] System info                         Home dir=C:\\Users\\Pro\\AppData\\Local\\Qitmeerd
2019-11-27|17:26:19.270 [INFO ] Loading block database              dbPath=C:\\Users\\Pro\\AppData\\Local\\Qitmeerd\\data\\testnet\\blocks_ffldb
2019-11-27|17:26:19.278 [INFO ] Block database loaded
2019-11-27|17:26:19.284 [INFO ] Starting Server                     module=node
2019-11-27|17:26:19.288 [INFO ] Transaction index is enabled        module=node
2019-11-27|17:26:19.288 [INFO ] anticone size:3                     module=blockdag
2019-11-27|17:26:19.289 [INFO ] Catching up indexes from order -1 to 0
2019-11-27|17:26:19.289 [INFO ] Indexes caught up to order 0
2019-11-27|17:26:19.289 [INFO ] DAG Type:phantom                    module=blockchain
2019-11-27|17:26:19.289 [INFO ] Blockchain database version         module=blockchain chain=1 compression=1 index=1
2019-11-27|17:26:19.289 [INFO ] Chain state:totaltx=1 tipsNum=1 mainOrder=0 total=1 module=blockchain
2019-11-27|17:26:19.289 [INFO ] hash=01fec9d4be0fe93b27261df1305b119573c5830002df5687aa05a4b79dd39615,order=0,work=34359754752 module=blockchain
2019-11-27|17:26:19.289 [INFO ] Starting tx manager                 module=txmanager
2019-11-27|17:26:19.292 [INFO ] Loaded 7 addresses from file 'C:\Users\Pro\AppData\Local\Qitmeerd\data\testnet\peers.json'
2019-11-27|17:26:19.292 [INFO ] Connection manager started
2019-11-27|17:26:19.294 [INFO ] P2P Server listening on             addr=[::]:18130
2019-11-27|17:26:19.301 [INFO ] P2P Server listening on             addr=0.0.0.0:18130
2019-11-27|17:26:19.304 [INFO ] RPC server listening on             addr=0.0.0.0:18131
2019-11-27|17:26:19.308 [INFO ] 6 addresses found from DNS seed testnet-seed.hlcwallet.info
2019-11-27|17:26:19.309 [INFO ] 6 addresses found from DNS seed testnet-seed.qitmeer.top
2019-11-27|17:26:19.314 [INFO ] New valid peer: 10.147.18.79:28130 (outbound),user-agent:qitmeer:0.8.2 module=blkmanager
2019-11-27|17:26:19.314 [INFO ] Syncing to state (0,0,0,1,1) from peer 10.147.18.79:28130 cur graph state:(0,0,0,1,1) module=blkmanager
2019-11-27|17:26:19.454 [ERROR] goroutine 87 [running]:
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).serveRequest.func1(0xc000118240, 0xe42b80, 0xc000162050)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:334 +0x12a
panic(0xb51ec0, 0xc000156690)
        C:/msys64/mingw64/lib/go/src/runtime/panic.go:679 +0x1c0
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).getBlock(...)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:518
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).GetMainParent(0xc0001038c0, 0xc0004980e8, 0x1, 0x1)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/core/blockdag/phantom.go:512 +0x16b
github.com/Qitmeer/qitmeer/core/blockdag.(*BlockDAG).CheckSubMainChainTip(0xc0001182d0, 0xc000498048, 0x1, 0x1, 0x0, 0x0)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/core/blockdag/blockdag.go:810 +0x12a
github.com/Qitmeer/qitmeer/services/miner.(*PublicMinerAPI).SubmitBlock(0xc000446c80, 0xc00136ec00, 0x3b8, 0x0, 0x0, 0x0, 0x0)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/services/miner/api.go:106 +0x1c7
reflect.Value.call(0xc0000569c0, 0xc000498120, 0x13, 0xc0b085, 0x4, 0xc0001564e0, 0x2, 0x2, 0x2, 0x18, ...)
        C:/msys64/mingw64/lib/go/src/reflect/value.go:460 +0x5fd
reflect.Value.Call(0xc0000569c0, 0xc000498120, 0x13, 0xc0001564e0, 0x2, 0x2, 0x1, 0x1, 0xc001389700)
        C:/msys64/mingw64/lib/go/src/reflect/value.go:321 +0xbb
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).handle(0xc000118240, 0xe3bd80, 0xc000054640, 0xe42b80, 0xc000162050, 0xc00011cc60, 0xc000162110, 0x0, 0xb45220)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:600 +0x6b8
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).exec(0xc000118240, 0xe3bd80, 0xc000054640, 0xe42b80, 0xc000162050, 0xc00011cc60)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:531 +0x1cb
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).serveRequest(0xc000118240, 0xe3be40, 0xc000156390, 0xe42b80, 0xc000162050, 0x1, 0x1, 0x0, 0x0)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:394 +0x403
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).ServeSingleRequest(...)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:318
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).jsonRPCRead(0xc000118240, 0xe39ec0, 0xc000172000, 0xc000094000)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:311 +0x50f
github.com/Qitmeer/qitmeer/rpc.(*RpcServer).startHTTP.func1(0xe39ec0, 0xc000172000, 0xc000094000)
        C:/msys64/home/Qitmeer/github.com/Qitmeer/qitmeer/rpc/rpcserver.go:182 +0x330
net/http.HandlerFunc.ServeHTTP(0xc00045ad70, 0xe39ec0, 0xc000172000, 0xc000094000)
        C:/msys64/mingw64/lib/go/src/net/http/server.go:2007 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0000c8340, 0xe39ec0, 0xc000172000, 0xc000094000)
        C:/msys64/mingw64/lib/go/src/net/http/server.go:2387 +0x1c4
net/http.serverHandler.ServeHTTP(0xc0001721c0, 0xe39ec0, 0xc000172000, 0xc000094000)
        C:/msys64/mingw64/lib/go/src/net/http/server.go:2802 +0xab
net/http.(*conn).serve(0xc000494820, 0xe3bd80, 0xc000054000)
        C:/msys64/mingw64/lib/go/src/net/http/server.go:1890 +0x87c
created by net/http.(*Server).Serve
        C:/msys64/mingw64/lib/go/src/net/http/server.go:2927 +0x395

**Comment by dindinw** [comment]
fixed by #196
