### ISSUE TITLE
Qitmeer crashes on launching  

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#343]
qitmeer wallet
1. update blocks
./qitmeer-wallet web

qitmeer node
./build/bin/qitmeer

020-07-29|17:23:03.560 [INFO ] System info                         Qitmeer Version=0.9.1+dev-e4b1919 Go version=go1.13.8
2020-07-29|17:23:03.560 [INFO ] System info                         UUID=3bc60bba-b203-4c39-a9b9-53fdccc62cbe
2020-07-29|17:23:03.560 [INFO ] System info                         Home dir=/home/ubuntu/.qitmeerd
2020-07-29|17:23:03.561 [INFO ] Loading block database              dbPath=/home/ubuntu/.qitmeerd/data/testnet/blocks_ffldb
2020-07-29|17:23:03.567 [INFO ] Detected unclean shutdown - Repairing... module=database
2020-07-29|17:23:03.568 [INFO ] Database sync complete              module=database
2020-07-29|17:23:03.568 [INFO ] Block database loaded
2020-07-29|17:23:03.569 [INFO ] Starting Server                     module=node
2020-07-29|17:23:03.570 [INFO ] Transaction index is enabled        module=node
2020-07-29|17:23:03.570 [INFO ] anticone size:4                     module=blockdag
2020-07-29|17:23:03.571 [INFO ] Loading dag ...                     module=blockchain
2020-07-29|17:23:05.470 [INFO ] Dag loaded:loadTime=1.897869437s    module=blockchain
2020-07-29|17:23:08.683 [INFO ] DAG Type:phantom                    module=blockchain
2020-07-29|17:23:08.684 [INFO ] Blockchain database version         module=blockchain chain=2 compression=1 index=1
2020-07-29|17:23:08.684 [INFO ] Chain state:totaltx=73109 tipsNum=1 mainOrder=69485 total=69486 module=blockchain
2020-07-29|17:23:08.684 [INFO ] hash=0002a608709b85e517deaede4a5722a5ca3135da5c89272dee126776c571d6e1,order=69485,work=43221570917030204608 module=blockchain
2020-07-29|17:23:08.684 [INFO ] ZMQ:Not Supported                   module=zmq
2020-07-29|17:23:08.685 [INFO ] Starting tx manager                 module=txmanager
2020-07-29|17:23:08.686 [INFO ] Loaded 20 addresses from file '/home/ubuntu/.qitmeerd/data/testnet/peers.json'
2020-07-29|17:23:08.686 [INFO ] Connection manager started
2020-07-29|17:23:08.686 [INFO ] RPC server listening on             addr=0.0.0.0:18131
2020-07-29|17:23:08.688 [WARN ] DNS discovery failed                seed=testnet-seed.hlcwallet.info error="lookup testnet-seed.hlcwallet.info: no such host"
2020-07-29|17:23:08.714 [INFO ] P2P Server listening on             addr=0.0.0.0:18130
2020-07-29|17:23:08.794 [INFO ] New valid peer: 47.103.61.128:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:08.795 [INFO ] Syncing to state (104267,101985,101985,104268,1) from peer 47.103.61.128:18130 cur graph state:(69485,68160,68160,69486,1) module=blkmanager
2020-07-29|17:23:08.804 [INFO ] New valid peer: 122.112.245.133:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:09.395 [INFO ] New valid peer: 104.224.174.141:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:09.879 [INFO ] New valid peer: 103.1.154.227:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:10.270 [INFO ] New valid peer: 144.202.90.65:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:11.686 [INFO ] Syncing to state (104267,101985,101985,104268,1) from peer 122.112.245.133:18130 cur graph state:(69985,68645,68645,69986,1) module=blkmanager
2020-07-29|17:23:11.698 [INFO ] 9 addresses found from DNS seed testnet-seed.qitmeer.xyz
2020-07-29|17:23:11.726 [WARN ] DNS discovery failed                seed=seed.qitmir.info            error="lookup seed.qitmir.info: Temporary failure in name resolution"
2020-07-29|17:23:15.256 [INFO ] Processed 908 blocks in the last 11.68s (918 transactions, order 70393, 2020-07-18 05:10:20 +0400 +04) module=blkmanager
2020-07-29|17:23:19.885 [INFO ] New valid peer: 106.15.102.183:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:21.415 [INFO ] New valid peer: 103.29.70.78:18130 (outbound),user-agent:qitmeer:0.9.1 module=blkmanager
2020-07-29|17:23:30.027 [INFO ] Processed 93 blocks in the last 14.77s (105 transactions, order 70486, 2020-07-18 05:48:53 +0400 +04) module=blkmanager
panic: runtime error: slice bounds out of range [:53] with capacity 51 [recovered]
	panic: runtime error: slice bounds out of range [:53] with capacity 51

goroutine 20 [running]:
github.com/Qitmeer/qitmeer/database/ffldb.rollbackOnPanic(0xc005c4b5f0)
	/home/ubuntu/github.com/qitmeer/qitmeer/database/ffldb/db.go:1891 +0x77
panic(0xc31ec0, 0xc0005341a0)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/Qitmeer/qitmeer/core/blockchain.decodeSpentTxOut(0xc001ae620d, 0x2e, 0x33, 0xc000098790, 0x59, 0x0, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/stxo.go:176 +0x3a7
github.com/Qitmeer/qitmeer/core/blockchain.deserializeSpendJournalEntry(0xc001ae61b0, 0x8b, 0x90, 0xc00aa3cdc8, 0x1, 0x1, 0x90, 0xf6, 0xf7, 0xc000559078, ...)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/stxo.go:213 +0x147
github.com/Qitmeer/qitmeer/core/blockchain.dbFetchSpendJournalEntry(0xef47e0, 0xc005c4b5f0, 0xc009af0cb0, 0x20, 0x18, 0xbff9c0, 0x42ecaa, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/stxo.go:271 +0x133
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).fetchSpendJournal.func1(0xef47e0, 0xc005c4b5f0, 0xc005c4b5f0, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:1188 +0x4b
github.com/Qitmeer/qitmeer/database/ffldb.(*db).View(0xc000060100, 0xc00b68cb80, 0x0, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/database/ffldb/db.go:1914 +0xb3
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).fetchSpendJournal(0xc0004a8240, 0xc009af0cb0, 0x2, 0x2, 0xedede0, 0x8, 0xc000559140)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:1185 +0x95
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).CalculateFees(0xc0004a8240, 0xc009af0cb0, 0xc009af0cb0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:1257 +0xcf
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).GetFees(0xc0004a8240, 0xc00b42f9c0, 0xc004618601)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:1283 +0x89
github.com/Qitmeer/qitmeer/core/blockchain.CheckTransactionInputs(0xc00c930b40, 0xc00bd777a0, 0x13b9240, 0xc0004a8240, 0xc000559778, 0xc0004a8240, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/validate.go:1090 +0x50e
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).checkTransactionsAndConnect(0xc0004a8240, 0xc00ba93c20, 0xc008488a10, 0xc0000fdf50, 0xc00bd777a0, 0xc000559778, 0x0, 0xc000047500)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/validate.go:877 +0x20d
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).checkConnectBlock(0xc0004a8240, 0xc00ba93c20, 0xc008488a10, 0xc00bd777a0, 0xc000559778, 0x8df530, 0xc008b523f0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/validate.go:786 +0x150
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).connectDagChain(0xc0004a8240, 0xc00ba93c20, 0xc008488a10, 0xc00487b080, 0x13e3490, 0x0, 0x0, 0x1, 0x0, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:733 +0x151
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc0004a8240, 0xc008488a10, 0x4, 0x0, 0x0)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/accept.go:169 +0x7bf
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc0004a8240, 0xc008488a10, 0xc000000004, 0xc002286a98, 0x1, 0x2)
	/home/ubuntu/github.com/qitmeer/qitmeer/core/blockchain/process.go:139 +0x4a8
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc0004a4690, 0xc007660450, 0x17)
	/home/ubuntu/github.com/qitmeer/qitmeer/services/blkmgr/handle_block.go:73 +0x27b
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc0004a4690)
	/home/ubuntu/github.com/qitmeer/qitmeer/services/blkmgr/blkmgr.go:515 +0xc99
created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
	/home/ubuntu/github.com/qitmeer/qitmeer/services/blkmgr/blkmgr.go:323 +0xbb

**Comment by forchain** [comment]
crashes on PR339 as well

**Comment by forchain** [comment]
1.  irreproducible on a fresh node, would be data problem, however, no message to direct me to clean up the ledger.
2. irrelevant to wallet, crashes independently

**Comment by forchain** [comment]
https://drive.google.com/file/d/1EkJiszpWin8aoe32ybBZUd870hUCYPuf/view?usp=sharing

ledger data

**Comment by lochjin** [comment]
Your database is too old. It belongs to the version before https://github.com/Qitmeer/qitmeer/commit/b6cb2c5fa5ad64001fedb3d141d5630636ca2d5b. It has to be rebuilt by --cleanup.

**Comment by forchain** [comment]
Verified

2020-08-10|13:34:14.012 [ERROR] Uable to start server               error="You can cleanup your block data base by '--cleanup'.The data is corrupted and cannot be upgraded (runtime error: slice bounds out of range [:52] with capacity 46). "
