### ISSUE TITLE
Qitmeer crash when execute `--droptxindex` command

### ISSUE THREAD

**Issue by dindinw** [Qitmeer/qitmeer#344]
```
$ ./build/bin/qitmeer --version
qitmeer version 0.9.1+dev-e4b1919 (Go version go1.14.4)

$ ./build/bin/qitmeer --droptxindex
2020-07-30|16:30:32.841 [WARN ] missing config file                 error="open /Users/alex/Library/Application Support/Qitmeerd/qitmeer.conf: no such file or directory"
2020-07-30|16:30:32.841 [INFO ] System info                         Qitmeer Version=0.9.1+dev-e4b1919 Go version=go1.14.4
2020-07-30|16:30:32.841 [INFO ] System info                         UUID=7b222595-31d7-454a-9291-38cb66ec1e0d
2020-07-30|16:30:32.841 [INFO ] System info                         Home dir="/Users/alex/Library/Application Support/Qitmeerd"
2020-07-30|16:30:32.841 [INFO ] Loading block database              dbPath="/Users/alex/Library/Application Support/Qitmeerd/data/mainnet/blocks_ffldb"
2020-07-30|16:30:32.873 [INFO ] Block database loaded
2020-07-30|16:30:32.873 [INFO ] Not dropping address index because it does not exist
2020-07-30|16:30:32.873 [INFO ] Dropping all transaction index entries.  This might take a while...
2020-07-30|16:30:32.873 [INFO ] Gracefully shutting down the database...
2020-07-30|16:30:32.894 [INFO ] Shutdown complete
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x165fbd0]

goroutine 1 [running]:
github.com/Qitmeer/qitmeer/database/ffldb.rollbackOnPanic(0xc000208360)
        /Users/alex/work/qitmeer/qitmeer/database/ffldb/db.go:1891 +0x77
panic(0x17a51e0, 0x1f929a0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/Qitmeer/qitmeer/services/index.incrementalFlatDrop.func1(0x1ad0ba0, 0xc000208360, 0x1f22ae8, 0xb, 0xb, 0x0, 0x0, 0x0, 0xc0001b7a88, 0x14d793d)
        /Users/alex/work/qitmeer/qitmeer/services/index/indexmgr.go:628 +0x250
github.com/Qitmeer/qitmeer/services/index.incrementalFlatDrop.func2(0x1ad0ba0, 0xc000208360, 0xc000208360, 0x0)
        /Users/alex/work/qitmeer/qitmeer/services/index/indexmgr.go:635 +0x68
github.com/Qitmeer/qitmeer/database/ffldb.(*db).View(0xc00002e140, 0xc00009a7e0, 0x0, 0x0)
        /Users/alex/work/qitmeer/qitmeer/database/ffldb/db.go:1914 +0x99
github.com/Qitmeer/qitmeer/services/index.incrementalFlatDrop(0x1ac8c60, 0xc00002e140, 0x1f22ae8, 0xb, 0xb, 0x1864b4d, 0x11, 0xc00008e2a0, 0x0, 0x0)
        /Users/alex/work/qitmeer/qitmeer/services/index/indexmgr.go:634 +0x138
github.com/Qitmeer/qitmeer/services/index.dropIndex(0x1ac8c60, 0xc00002e140, 0x1f22ae8, 0xb, 0xb, 0x1864b4d, 0x11, 0xc00008e2a0, 0x0, 0x0)
        /Users/alex/work/qitmeer/qitmeer/services/index/indexmgr.go:741 +0x20e
github.com/Qitmeer/qitmeer/services/index.DropTxIndex(0x1ac8c60, 0xc00002e140, 0xc00008e2a0, 0x0, 0x0)
        /Users/alex/work/qitmeer/qitmeer/services/index/txindex.go:584 +0xfd
main.qitmeerdMain(0x0, 0x0, 0x0)
        /Users/alex/work/qitmeer/qitmeer/cmd/qitmeerd/qitmeerd.go:97 +0x99c
main.main()
        /Users/alex/work/qitmeer/qitmeer/cmd/qitmeerd/qitmeerd.go:33 +0x47
```

**Comment by dindinw** [comment]
not a bug, due to the corrupted data
