### ISSUE TITLE
[0.10.0-dev]Crash on launching

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#394]
possible reproduction steps

1. clean build
2. wait until synchronization done
3. force kill process
4. launch

```shell
2020-11-14|07:29:52.515 [INFO ] 16Uiu2HAmHoq3MqSt7YyGeqr5b5eq3aeYdFE8UkJRT9d1YFVZwPeF direction:Outbound multiAddr:/ip4/144.202.90.65/tcp/28130/p2p/16Uiu2HAmHoq3MqSt7YyGeqr5b5eq3aeYdFE8UkJRT9d1YFVZwPeF activePeers:3 Peer Connected module=SYNC
panic: interface conversion: blockdag.IBlock is nil, not *blockdag.PhantomBlock

goroutine 133 [running]:
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).getBlock(...)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockdag/phantom.go:543
github.com/Qitmeer/qitmeer/core/blockdag.(*Phantom).UpdateWeight(0xc00072e180, 0x20fbc40, 0xc0009e6220, 0x20fbc01)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockdag/phantom.go:738 +0x3e7
github.com/Qitmeer/qitmeer/core/blockdag.(*BlockDAG).UpdateWeight(...)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockdag/blockdag.go:1377
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).updateBestState(0xc00073e000, 0xc006c990e0, 0xc00698d340, 0xc0067f1170, 0x28bc4c8, 0x0)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockchain/blockchain.go:833 +0x145
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc00073e000, 0xc00698d340, 0x4, 0x0, 0x0)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockchain/accept.go:172 +0x8e9
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc00073e000, 0xc00698d340, 0x4, 0xc00698d340, 0x0, 0x0)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockchain/process.go:139 +0x790
github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).processGetBlockDatas(0xc0006ea070, 0xc006d18140, 0xc0000f3000, 0x7d0, 0x900, 0x0, 0x0)
        /Users/Outlier/github.com/qitmeer/qitmeer/p2p/synch/getblockdatas.go:143 +0x507
github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).handler(0xc0006ea070)
        /Users/Outlier/github.com/qitmeer/qitmeer/p2p/synch/peersync.go:93 +0x775
created by github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).Start
        /Users/Outlier/github.com/qitmeer/qitmeer/p2p/synch/peersync.go:52 +0x10b
```

**Comment by forchain** [comment]
possible due to MacOS Big Sur

**Comment by forchain** [comment]
Trace log and block data

Click link: https://cowtransfer.com/s/259489245ed248 or use code:576513 to receive your file on cowtransfer.com

**Comment by forchain** [comment]
by design
