### ISSUE TITLE
Crash due to too many open files opened

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#423]
Qitmeer wallet sync blocks

```
2021/01/30 15:02:43 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 1s
2021/01/30 15:02:44 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 1s
2021/01/30 15:03:13 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 5ms
2021/01/30 15:03:14 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 5ms
2021/01/30 15:03:43 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 10ms
2021/01/30 15:03:43 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 20ms
2021/01/30 15:04:13 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 40ms
2021/01/30 15:04:13 http: Accept error: accept tcp4 0.0.0.0:18131: accept: too many open files; retrying in 80ms
2021-01-30|15:04:18.555 [ERROR] Error opening file %s: %v           /Users/Outlier/Library/Application Support/Qitmeerd/data/testnet/peers.json.new="open /Users/Outlier/Library/Application Support/Qitmeerd/data/testnet/peers.json.new: too many open files"
panic: failed to commit leveldb transaction: open /Users/Outlier/Library/Application Support/Qitmeerd/data/testnet/blocks_ffldb/metadata/016055.ldb: too many open files

goroutine 66 [running]:
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).maybeAcceptBlock(0xc000382100, 0xc032e88000, 0x4, 0x0, 0x0)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockchain/accept.go:143 +0xc6d
github.com/Qitmeer/qitmeer/core/blockchain.(*BlockChain).ProcessBlock(0xc000382100, 0xc032e88000, 0xc000000004, 0xc043599d28, 0x1, 0x2)
        /Users/Outlier/github.com/qitmeer/qitmeer/core/blockchain/process.go:139 +0x790
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).handleBlockMsg(0xc000382000, 0xc053a34690, 0x17)
        /Users/Outlier/github.com/qitmeer/qitmeer/services/blkmgr/handle_block.go:73 +0x297
github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).blockHandler(0xc000382000)
        /Users/Outlier/github.com/qitmeer/qitmeer/services/blkmgr/blkmgr.go:519 +0xc33
created by github.com/Qitmeer/qitmeer/services/blkmgr.(*BlockManager).Start
        /Users/Outlier/github.com/qitmeer/qitmeer/services/blkmgr/blkmgr.go:327 +0xbc

```

**Comment by forchain** [comment]
wallet
```
Outlier@Mac ~/github.com/forchain/qitmeer-wallet (master*) $ ./qitmeer-wallet web
web model
update blcok:630890/677143
```
qitmeer
```
2021-01-30|15:33:09.356 [INFO ] Processed 1 block in the last 12.75s (1 transaction, order 677147, 2021-01-30 15:32:56 +0800 CST) module=blkmanager
2021-01-30|15:33:09.356 [INFO ] Your synchronization has been completed.  module=blkmanager
2021-01-30|15:33:14.413 [INFO ] Your synchronization has been completed.  module=blkmanager


```
wallet synchronization is normal at the beginning and no such error appears in qitmeer.


Once wallet sync is over, the errors come up

**Comment by forchain** [comment]
cannot reproduce
