### ISSUE TITLE
[0.10-dev]qitmeer crashes

### ISSUE THREAD

**Issue by forchain** [Qitmeer/qitmeer#474]
### build 
f2305f24

### logs

2021-04-11|10:46:45.880 [INFO ] peer:16Uiu2HAm3gKfGGkHCikustscQ35CMPqTwg3iHWT7o4HzMF5oBXSh Peer Disconnected,activePeers:4 module=SYNC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf38738]

goroutine 76 [running]:
github.com/Qitmeer/qitmeer/p2p/peers.(*Peer).IsActive(0x0, 0x0)
        /home/tony/github.com/qitmeer/0.10-dev/p2p/peers/peer.go:185 +0x38
github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).OnPeerUpdate(0xc000542080, 0xc008fd82d0, 0x0)
        /home/tony/github.com/qitmeer/0.10-dev/p2p/synch/peersync.go:219 +0x7d
github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).handler(0xc000542080)
        /home/tony/github.com/qitmeer/0.10-dev/p2p/synch/peersync.go:108 +0x426
created by github.com/Qitmeer/qitmeer/p2p/synch.(*PeerSync).Start
        /home/tony/github.com/qitmeer/0.10-dev/p2p/synch/peersync.go:55 +0x10f

**Comment by forchain** [comment]
not reproduced
